version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/application
hooks:
  AfterInstall:
   - location: application/scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: application/scripts/start_server
     timeout: 300
     runas: root
